"""Add added_by column to corpora

Revision ID: 077f74f56973
Revises: eb6df6c4c8a5
Create Date: 2019-09-30 09:50:45.922693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '077f74f56973'
down_revision = 'eb6df6c4c8a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corpora', sa.Column('added_by', sa.Integer(), nullable=True), schema='keopsdb')
    op.create_foreign_key(op.f('corpora_added_by_fkey'), 'corpora', 'users', ['added_by'], ['id'], source_schema='keopsdb', referent_schema='keopsdb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('corpora_added_by_fkey'), 'corpora', schema='keopsdb', type_='foreignkey')
    op.drop_column('corpora', 'added_by', schema='keopsdb')
    # ### end Alembic commands ###
