"""Add tasks information

Revision ID: 1ec316af4a8f
Revises: 241a1d4de4e1
Create Date: 2019-09-18 13:13:52.917726

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1ec316af4a8f'
down_revision = '241a1d4de4e1'
branch_labels = None
depends_on = None


def upgrade():
    modeEnum = sa.Enum('VAL', 'ADE', 'FLU', 'RAN', name='evalmode', create_type=True, schema='keopsdb')

    op.execute("""
        CREATE TYPE keopsdb.evalmode AS ENUM ('VAL', 'ADE', 'FLU', 'RAN');
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('score', sa.Numeric(), nullable=True), schema='keopsdb')
    # ### end Alembic commands ###
    op.add_column('tasks', sa.Column('evalmode', modeEnum, nullable=True), schema='keopsdb')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'score', schema='keopsdb')
    op.drop_column('tasks', 'evalmode', schema='keopsdb')
    # ### end Alembic commands ###

    op.execute("""
        DROP TYPE IF EXISTS keopsdb.evalmode
    """)