"""Add sentence information

Revision ID: 241a1d4de4e1
Revises: bea5d762a752
Create Date: 2019-09-18 13:12:22.611325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241a1d4de4e1'
down_revision = 'bea5d762a752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('system', sa.String(length=140), nullable=True), schema='keopsdb')
    op.add_column('sentences', sa.Column('type', sa.String(length=140), nullable=True), schema='keopsdb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentences', 'type', schema='keopsdb')
    op.drop_column('sentences', 'system', schema='keopsdb')
    # ### end Alembic commands ###
