"""Set null evalmodes to VAL

Revision ID: 64d08233eefa
Revises: 4674a545b1b0
Create Date: 2019-09-18 15:26:09.639667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64d08233eefa'
down_revision = '4674a545b1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        update keopsdb.tasks set evalmode = 'VAL'::keopsdb.evalmode where evalmode is null;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
