"""Add feedback table

Revision ID: 84c03f89212d
Revises: 64d08233eefa
Create Date: 2019-09-19 08:38:49.937987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84c03f89212d'
down_revision = '64d08233eefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=240), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], [u'keopsdb.tasks.id'], name=op.f('feedback_task_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], [u'keopsdb.users.id'], name=op.f('feedback_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey')),
    schema='keopsdb'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback', schema='keopsdb')
    # ### end Alembic commands ###
