"""Add Comments table

Revision ID: 9e93ad2ab9f9
Revises: 39f0aae0582b
Create Date: 2019-09-18 12:10:43.947624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e93ad2ab9f9'
down_revision = '39f0aae0582b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('pair', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pair'], [u'keopsdb.sentences_tasks.id'], name=op.f('comments_pair_fkey')),
    sa.PrimaryKeyConstraint('pair', 'name', name=op.f('comments_pkey')),
    schema='keopsdb'
    )
    # ### end Alembic commands ###

    op.execute("""
        insert into keopsdb.comments (pair, name, value) 
        (select id, 'X_LegacyComments', CAST(comments as VARCHAR(255)) from keopsdb.sentences_tasks where comments is not null and comments != '');
    """)

def downgrade():
    op.execute("""
        update keopsdb.sentences_tasks
        set comments = keopsdb.comments.value
        from keopsdb.comments where pair = id and name = 'X_LegacyComments';
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments', schema='keopsdb')
    # ### end Alembic commands ###
