"""Add vector

Revision ID: bea5d762a752
Revises: 552fb76000a5
Create Date: 2019-09-18 13:09:06.926723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bea5d762a752'
down_revision = '552fb76000a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('source_text_vector', postgresql.TSVECTOR(), nullable=True), schema='keopsdb')
    # ### end Alembic commands ###

    op.execute("""
        CREATE TEXT SEARCH DICTIONARY public.simple_dict ( TEMPLATE = pg_catalog.simple );
    """)

    op.execute("""
        update keopsdb.sentences set source_text_vector = to_tsvector('simple', source_text)
    """)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentences', 'source_text_vector', schema='keopsdb')
    # ### end Alembic commands ###

    op.execute("""
        DROP TEXT SEARCH DICTIONARY IF EXISTS public.simple_dict
    """)
