"""Add time column

Revision ID: c0f84decbdac
Revises: b8bec0892316
Create Date: 2019-09-18 13:17:42.593851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f84decbdac'
down_revision = 'b8bec0892316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences_tasks', sa.Column('time', sa.Numeric(), nullable=True), schema='keopsdb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentences_tasks', 'time', schema='keopsdb')
    # ### end Alembic commands ###
