"""Add root role

Revision ID: ce8a8c9313da
Revises: 077f74f56973
Create Date: 2019-09-30 10:05:37.242302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce8a8c9313da'
down_revision = '077f74f56973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("""
        ALTER TABLE keopsdb.users ALTER COLUMN role TYPE VARCHAR(255);
        ALTER TABLE keopsdb.users ALTER COLUMN role DROP DEFAULT;
        DROP TYPE IF EXISTS keopsdb.role;
        CREATE TYPE keopsdb.role AS ENUM ('ADMIN', 'PM', 'USER', 'root');
        ALTER TABLE keopsdb.users ALTER COLUMN role TYPE keopsdb.role USING (role::keopsdb.role);
        ALTER TABLE keopsdb.users ALTER COLUMN role SET DEFAULT 'USER'::keopsdb.role;
    """)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    op.execute("""
        ALTER TABLE keopsdb.users ALTER COLUMN role TYPE VARCHAR(255);
        ALTER TABLE keopsdb.users ALTER COLUMN role DROP DEFAULT;
        DROP TYPE IF EXISTS keopsdb.role;
        CREATE TYPE keopsdb.role AS ENUM ('ADMIN', 'PM', 'USER');
        ALTER TABLE keopsdb.users ALTER COLUMN role TYPE keopsdb.role USING (role::keopsdb.role);
        ALTER TABLE keopsdb.users ALTER COLUMN role SET DEFAULT 'USER'::keopsdb.role;
    """)