"""Add password renew table

Revision ID: eb6df6c4c8a5
Revises: e6e3690332da
Create Date: 2019-09-23 14:05:52.831238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb6df6c4c8a5'
down_revision = 'e6e3690332da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_renew',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'keopsdb.users.id'], name=op.f('password_renew_user_fkey')),
    sa.PrimaryKeyConstraint('token', name=op.f('password_renew_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('password_renew_user_key')),
    schema='keopsdb'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_renew', schema='keopsdb')
    # ### end Alembic commands ###
