"""Change admin to PM

Revision ID: ed9f000d6608
Revises: f5d33dd928d1
Create Date: 2019-10-01 10:40:31.123618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed9f000d6608'
down_revision = 'f5d33dd928d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        update keopsdb.users set role = 'PM' where role = 'ADMIN';
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        update keopsdb.users set role = 'ADMIN' where role = 'PM';
    """)
    # ### end Alembic commands ###
