"""Move languages to Tasks

Revision ID: f5ba8fc1c5da
Revises: 9e93ad2ab9f9
Create Date: 2019-09-18 12:32:38.650353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ba8fc1c5da'
down_revision = '9e93ad2ab9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'projects_source_lang_fkey', 'projects', schema='keopsdb', type_='foreignkey')
    op.drop_constraint(u'projects_target_lang_fkey', 'projects', schema='keopsdb', type_='foreignkey')
    op.add_column('tasks', sa.Column('source_lang', sa.String(length=5), nullable=True), schema='keopsdb')
    op.add_column('tasks', sa.Column('target_lang', sa.String(length=5), nullable=True), schema='keopsdb')
    op.create_foreign_key(op.f('tasks_source_lang_fkey'), 'tasks', 'langs', ['source_lang'], ['langcode'], source_schema='keopsdb', referent_schema='keopsdb')
    op.create_foreign_key(op.f('tasks_target_lang_fkey'), 'tasks', 'langs', ['target_lang'], ['langcode'], source_schema='keopsdb', referent_schema='keopsdb')
    # ### end Alembic commands ###

    op.execute("""
        update keopsdb.tasks as t set source_lang = l1.langcode, target_lang = l2.langcode
        from keopsdb.projects as p, keopsdb.langs as l1, keopsdb.langs as l2
        where p.id = t.project_id and l1.id = p.source_lang and l2.id = p.target_lang
    """)

    op.drop_column('projects', 'target_lang', schema='keopsdb')
    op.drop_column('projects', 'source_lang', schema='keopsdb')

def downgrade():
    op.add_column('projects', sa.Column('source_lang', sa.INTEGER(), autoincrement=False, nullable=True), schema='keopsdb')
    op.add_column('projects', sa.Column('target_lang', sa.INTEGER(), autoincrement=False, nullable=True), schema='keopsdb')

    op.execute("""
        update keopsdb.projects as p set source_lang = l1.id, target_lang = l2.id
        from keopsdb.tasks as t, keopsdb.langs as l1, keopsdb.langs as l2
        where p.id = t.project_id and l1.langcode = t.source_lang and l2.langcode = t.target_lang
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_target_lang_fkey'), 'tasks', schema='keopsdb', type_='foreignkey')
    op.drop_constraint(op.f('tasks_source_lang_fkey'), 'tasks', schema='keopsdb', type_='foreignkey')
    op.drop_column('tasks', 'target_lang', schema='keopsdb')
    op.drop_column('tasks', 'source_lang', schema='keopsdb')
    op.create_foreign_key(u'projects_target_lang_fkey', 'projects', 'langs', ['target_lang'], ['id'], source_schema='keopsdb', referent_schema='keopsdb')
    op.create_foreign_key(u'projects_source_lang_fkey', 'projects', 'langs', ['source_lang'], ['id'], source_schema='keopsdb', referent_schema='keopsdb')
    # ### end Alembic commands ###
