"""Add root user

Revision ID: f5d33dd928d1
Revises: ce8a8c9313da
Create Date: 2019-09-30 14:32:36.585448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5d33dd928d1'
down_revision = 'ce8a8c9313da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        insert into keopsdb.users (id, name, email, role, password) values (-1, 'root', 'root', 'root', '$2y$10$rUSV39GMx2fy9XTFT.CdVOlKuNpGxDKazJyzqRS8n3D0Z9mKgBdRi') on conflict do nothing;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        delete from keopsdb.users where role = 'root';
    """)    # ### end Alembic commands ###
